#index:
#    path: /
#    controller: App\Controller\DefaultController::index

redirects:
    resource: App\Controller\RedirectedController
    type: annotation

pages:
    resource: App\Controller\PagesController
    type: annotation

#controllers:
#    resource: '../src/Controller/'
#    type: annotation
